export const data = [
    ['What is the most popular programing language in 2024?',
        'JavaScript', 'Java', 'Python', 'C#',
        'a'],
    ['What is a Class in JavaScript?',
        'A factory function', 'An array creator', 'A blueprint for creating objects', 'None of the above',
        'c'],
    ['Can you use a function to create an object in JavaScript?',
        'No', 'Yes', 'Only in some occasions', 'You can, but you should not.',
        'b'],
    ['What is inheritance in JavaScript?',
        'Taking the money from your relative after he passes away',
        'functions getting functionality from other functions',
        'There is no such thing', 'Classes inheriting the properties and methods from other classes',
        'd'],
    ['What does DOM mean?',
        'Document Oriented Mainstream',
        'Doctors Office Managment',
        'Document Object Model',
        'Directly Oriented Manipulation',
        'c'],
    ['What does HTTP mean?',
        'Hypertext Transfer Protocol',
        'Hypermilage Turbo Training Pilot',
        'Hypertext Trajectory Prototype',
        'Hybrid Text Transfer Protocol',
        'a'],
    ['What does Object.assign do?',
        'Assigns values to an array',
        'Assigns a method to a given object',
        'Assigns a prototype to an object',
        'Assigns all enumerable properties of a source object to a target object',
        'd'],
]